// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:                   string;
  type:                 string;
  place_type:           string[];
  relevance:            number;
  properties:           Properties;
  text_es:              string;
  place_name_es:        string;
  text:                 string;
  place_name:           string;
  matching_place_name?: string;
  center:               number[];
  geometry:             Geometry;
  address?:             string;
  context:              Context[];
  bbox?:                number[];
}

export interface Context {
  id:           string;
  text_es:      string;
  text:         string;
  short_code?:  ShortCode;
  wikidata?:    string;
  language_es?: Language;
  language?:    Language;
}

export enum Language {
  Es = "es",
}

export enum ShortCode {
  Cl = "cl",
  ClBI = "CL-BI",
}

export interface Geometry {
  type:        string;
  coordinates: number[];
}

export interface Properties {
  accuracy?: string;
}
